-
  branches:
    only:
      - master

  version: 1.5.1

  install:
    - ps : .\environment-install.ps1

  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true

  os: Visual Studio 2015

  before_build:
    - ps : .\build-before_build.ps1

  build:
    parallel: true
    verbosity: normal
    publish_nuget: true

  environment:
    CompaniesHouseApiKey:
      secure: Fc+nnp3vXkqInQmAJ1l8OmuEKPgcBQG7cz5FPmiUZPUyh3apYnE8S+bDip7FNzq4

  configuration: Release

  cache:
    - packages -> **\packages.config
    - C:\downloads -> appveyor.yml

  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
      - '**\*..IntegrationTests.dll'

  artifacts:
    - path: '*.nupkg'

  deploy:
    - provider: Environment
      name: NuGet.org

-
  branches:
    except:
      - master

  version: 0.0.0-{branch}{build}

  install:
    - ps : .\environment-install.ps1

  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true

  os: Visual Studio 2015

  before_build:
    - ps : .\build-before_build.ps1

  build:
    parallel: true
    verbosity: normal
    publish_nuget: true

  environment:
    CompaniesHouseApiKey:
      secure: Fc+nnp3vXkqInQmAJ1l8OmuEKPgcBQG7cz5FPmiUZPUyh3apYnE8S+bDip7FNzq4

  configuration: Release

  cache:
    - packages -> **\packages.config
    - C:\downloads -> appveyor.yml

  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
      - '**\*..IntegrationTests.dll'

  artifacts:
    - path: '*.nupkg'
